### ISSUE TITLE
Setup module fails on azure VM build with no error

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/packer-plugin-ansible#148]
#### Overview of the Issue

When using the ansible provisioner within a pipeline the `setup` module fails with no outputted error.

packer build stdout with `PACKER_LOG=1`:

```
    azure-arm.centos: verbosity: 4
    ...
    azure-arm.centos: task path: /<>/packer-image-factory/playbooks/playbook.yml:5
2023/04/06 13:07:06 packer-provisioner-ansible plugin: SSH proxy: accepted connection 
==> azure-arm.centos: Provisioning step had errors: Running the cleanup provisioner, if present...
```
`playbook.yaml:5` is the setup module

Y'alls docs has a [troubleshooting note](https://github.com/hashicorp/packer-plugin-ansible/blob/main/docs/provisioners/ansible.mdx?plain=1#L804)

> If you are using an Ansible version >= 2.8 and Packer hangs in the
"Gathering Facts" stage, this could be the result of a pipelineing issue with
the proxy adapter that Packer uses. Setting `set_proxy` to `false` in your
Packer config should resolve the issue.

This sounds pretty similar but, as far as i can tell... 1. its not "hanging" 2. i cannot find a `set_proxy` parameter in any block resource definition for packer.

#### Reproduction Steps

Ansible playbook:

```
---
- hosts: default
  gather_facts: false
  tasks:
    - name: Gather Facts Subset
      become: true
      setup:
        gather_subset:
          - date_time
```

Packer config:

```
locals {
  packerstarttime = formatdate("YYYY-MM-DD-hhmm", timestamp())
}

source "azure-arm" "centos" {
  azure_tags      = merge(var.tags, {
    packerstarttime = local.packerstarttime
  })
  image_offer     = "CentOS"
  image_publisher = "OpenLogic"
  image_sku       = "8.0"
  image_version   = "latest"
  os_type         = "Linux"
  vm_size         = "Standard_D2_v2"
  os_disk_size_gb = "100"
  location        = "eastus"

  managed_image_name                = "centos-pkr"
  managed_image_resource_group_name = "packer-demo"

  client_id       = var.client_id
  client_secret   = var.client_secret
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

build {
  sources = ["source.azure-arm.centos"]

  provisioner "ansible" {
    ansible_env_vars = [
      "ANSIBLE_HOST_KEY_CHECKING=False",
      "ANSIBLE_NOCOWS=1",
      // https://dev.to/cosimo/failed-to-connect-to-the-host-via-ssh-on-ubuntu-2204-3odl
      "ANSIBLE_SSH_ARGS='-o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostkeyAlgorithms=+ssh-rsa'"
    ]
    extra_arguments  = [
      "--extra-vars",
      "desktop=false",
      "-vvvv",
      // https://github.com/kubernetes-sigs/image-builder/issues/859#issuecomment-1183566707
      "--scp-extra-args", "'-O'"
    ]
    playbook_file    = "${path.root}/../playbooks/playbook.yml"
    user             = "ubuntu"
  }

  post-processor "manifest" {
    output = "packer-manifest-azure.json"
  }
}
```

gitlab pipeline file:

```
stages:
  - packer

packer-build-azure:
  image:
    name: drewmullen/pkr-ans:latest
  stage: packer
  script:
    - "packer build -var client_id=$ARM_CLIENT_ID -var client_secret=$ARM_CLIENT_SECRET -var subscription_id=$ARM_SUBSCRIPTION_ID -var tenant_id=$ARM_TENANT_ID ./centos/"
  artifacts:
    paths:
      - packer-manifest-azure.json
```

### Plugin and Packer version

ansible-playbook [core 2.14.4]
packer 1.6.6

### Operating system and Environment details

gitlab ci

**NOTE** this build works fine locally on my macbook

### Log Fragments and crash.log files

see above error
