### ISSUE TITLE
Support for builder lxd in combination with ansible

### ISSUE THREAD

**Issue by keestux** [hashicorp/packer-plugin-ansible#95]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

The combination of builder type `lxd` is not working with provisioner `ansible`.

The work around is to user the `ansible-local` provisioner, but then you need to install the `ansible` package in the container before being able to run the ansible stuff.

#### Use Case(s)

Create preconfigured LXC images, as you can do for other builder types.

#### Potential configuration

```
{
  "builders": [
    {
      "type": "lxd",
      "name": "lxd-focal",
      "image": "ubuntu:focal",
      "output_image": "focal-apache2",
      "publish_properties": {
        "description": "Trivial repackage ubuntu:focal with Packer"
      }
    }
  ],
  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "./install-apache.yaml"
    }
  ]
}
```

The workaround is to use `ansible-local`, as follows:
```
{
  "builders": [
    {
      "type": "lxd",
      "name": "lxd-focal",
      "image": "ubuntu:focal",
      "output_image": "focal-apache2",
      "publish_properties": {
        "description": "Trivial repackage ubuntu:focal with Packer"
      }
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": ["apt update"]
    },
    {
      "type": "shell",
      "inline": ["apt install -y ansible"]
    },
    {
      "type": "ansible-local",
      "playbook_file": "./install-apache.yaml"
    }
  ]
}
```

The ansible playbook for this example:
```
---
- name: 'Provision Image With Apache2'
  hosts: localhost

  tasks:
  - name: Install Apache2
    ansible.builtin.apt:
      name: apache2
      state: present
```
#### Potential References

There is a great video by Stéphane Graber on youtube explaining how LXD and Ansible work together. Search for "LXD and Ansible".

**Comment by itoffshore** [comment]
the **ansible provisioner** works perfectly with the ansible `lxd` connection plugin [community.general.lxd](https://docs.ansible.com/ansible/latest/collections/community/general/lxd_connection.html#ansible-collections-community-general-lxd-connection)

**Comment by keestux** [comment]
@itoffshore can you show me a small example. Because the example above doesn't work.

**Comment by itoffshore** [comment]
@keestux - use [HCL2 style templating](https://www.packer.io/docs/templates/hcl_templates) (not `json` as you are above) - I put an [example on Stack Exchange](https://serverfault.com/a/1096671/246407) - with values hardcoded.

I now configure various variables which you will see in the HCL example below. Ultimately you want to aim for nothing hardcoded in your HCL template.

basic `ansible` configuration:

```
# ansible/inventory.yml

default:
  hosts:
    127.0.0.1:
      ansible_python_interpreter: "/usr/bin/python3"
      ansible_connection: lxd

# ansible/playbook.yml

---
 - name: Install Packages
   hosts: default
   gather_facts: no

   tasks:
     - name: Install ubuntu-base packages
       when: build_template == "ubuntu-base"
       apt:
         pkg:
         - curl
```


HCL template
```
source "lxd" "master" {
  
  image = "${var.lxd_remote}:${local.final_img}"
  output_image = "${local.output_image}"

  publish_properties = {
        description = "IAC image: ${local.output_image}"
  }
}


build {
  # using vars for sources triggers double build errors
  # this references the above source block
  sources = ["source.lxd.master"]

# install python3 (either Packer shell provisioner or Ansible)

...

# configure container
  provisioner "ansible" {
        user = "root"
        playbook_file = "${path.cwd}/ansible/playbook.yml"
        inventory_file = "${path.cwd}/ansible/inventory.yml"
        ansible_env_vars = [
                "ANSIBLE_NOCOLOR=True",
        ]

        # NB: ansible_host set here
        # also an example of passing variables to ansible & running verbosely
        extra_arguments = [ "--extra-vars=build_template=${local.build_template} ansible_host=packer-${source.name}, "-vvv"" ]
  }

# shell provsioners
...
# post processors
...


}

```

My file structure looks like:
```
├── locals.pkr.hcl
├── set.variables.pkr.hcl
├── template-lxd-master.pkr.hcl
├── var.alpine-base.pkrvars.hcl
├── var.alpine-lxd.pkrvars.hcl
├── var.ubuntu-base.pkrvars.hcl
└── var.ubuntu-k3s.pkrvars.hcl
```

In this way I can run builds with specific variables set e.g:

```
packer validate -var-file=var.ubuntu-base.pkrvars.hcl .
packer build -only lxd.master -var-file=var.ubuntu-base.pkrvars.hcl .
```

NB: the dot at the end of the above 2 commands to source all the variable files

**Comment by keestux** [comment]
Thanks for the help.

Well, I wanted to start with a (small) hardcoded example. But the one on Stack Exchange is using a shell provisioner. And I want to see something working with ansible. On the other hand the example above is giving an idea how to set it up properly with multiple HCL files. I need some help with the `extra_arguments`, perhaps hardcoded.

**Comment by keestux** [comment]
Back to why my original example didn't work. The essential part is that (intermediate) container is named: `packer-<name-from-build-config>`. In my example (above) that should have been `packer-lxd-focal`, not `localhost`. This name has to be given in the inventory.

So the complete example (in `json` format):
```json
{
  "builders": [
    {
      "type": "lxd",
      "name": "lxd-focal",
      "image": "ubuntu:focal",
      "output_image": "focal-apache2",
      "publish_properties": {
        "description": "Trivial repackage ubuntu:focal+apache2 with Packer"
      }
    }
  ],
  "provisioners": [
      {
        "type": "ansible",
        "playbook_file": "ansible/playbook.yml",
        "inventory_file": "ansible/inventory.yml"
      }
  ]
}
```

Ansible inventory `ansible/inventory.yml`:
```yaml
default:
  hosts:
    packer-lxd-focal:
      ansible_connection: lxd
```

Ansible playbook `ansible/playbook.yml`:
```yaml
---
- name: Install Packages
  hosts: default
  gather_facts: yes

  tasks:
  - name: Install some packages
    ansible.builtin.apt:
      name:
      - apache2
      state: present
```

Final word for @itoffshore . The HCL format is indeed a better choice for packer configs. But that did not help to figure out what was wrong in the first place.
